### PR TITLE
Data oriented design

### PR DESCRIPTION
**Pull request by thatswonderfool**
After viewing the [video by Cherno](https://www.youtube.com/watch?v=mOSirVeP5lo), I tried to improve the code using some [data oriented design](https://www.youtube.com/watch?v=rX0ItVEVjHc). I managed to get it about 7 times faster.
I removed the indirect access via std::variant, separated geometry from material and removed detrimental indirections and unnecessary computations like normalizing Rays for each bounce.

### CODE REVIEW

**Comment by valerioformato** [comment]
Wow, thanks for your contribution, this is a clear example of how much performance gain is still on the table for the project!

However, there are several aspects of this implementation that I would like to adopt, and several that conflict with how I want the project to be organized.
For example, it's okay to separate geometry and materials from each other, but I don't like the proliferation of the `Add` methods in the `HittableObjectList` class, and in general how any addition to both shapes and materials requires heavy refactoring of the code, hence the use of `variant` in this stage of the project. (I still have to go through and investigate the overhead in compiler explorer)
I'd like to keep the logic independent on how many shapes and materials are supported in the project, at least in this initial prototyping stage.
Still, I'll bring in all optimizations that don't require an immediate and drastic design rework.

All signs actually point towards the integration of a entity/component system like `entt`, and I have been thinking about that for some time.

**Comment by thatswonderfool** [comment]
I see your point about the proliferation of the `Add` methods. I've reintroduced `std::variant` for materials. This has only a minor impact on performance as the material is only accessed seldom relative to the geometry.

**Comment by valerioformato** [comment]
Thanks for understanding, I'll look more closely at it once I get home (and have some spare time).

**Comment by valerioformato** [comment]
Sorry for the delay, this took me longer than I expected. There are a lot of good ideas in this PR but, unfortunately, in can't take it in as is.

This is especially due to commit 8eff7ab which really makes it extremely hard to add new shapes to the render. I feel that this particular optimization only applies to the particular case where only spheres are present and, since I'm planning to add quads and cubes soon, I cant bring it in as it is.

I take some time and went through all proposed changes, tested them in isolation and implemented those that brought a speedup in a separate branch, you can take a look (#5).

Overall this brought a factor 2.6x speedup and I am extremely grateful, there is still a 40% left somewhere on the table (I run the default scene on your branch, it took ~9s, meaning that without commit 8eff7ab it should take ~18s. The code on #5 takes ~24s, this is where 40% comes from) but I feel like that will be much harder to track down, and I really want to add new features!

I'd like to add you to the contributors, but I won't be merging this PR. I'll add a README or something like that and maybe you can commit your name in so you'll appear on the main github page?

**Comment by thatswonderfool** [comment]
I'm glad you could adopt some of my performance improvements and thank you for the offer to add my name.

Regarding commit 8eff7ab I still think this is easily extendable to more shape types. This is a conceptual question: who is responsible for computing the distance to the object? Is it the object `Sphere` itself (object oriented design) or is it the `Hit` method (data oriented design)? I'm still in huge favor of my solution and think it is cleaner. To have `variant::visit()` in your hot loop is really inefficient (and obfuscates the code), because this requires dynamic dispatch for each object in your scene. Instead, I would suggest a loop for each shape type (i.e. find closest sphere, cube, ... separately). But I won't stop you from doing it in your own style.

It's unfortunate that it took me multiple commits to arrive at a presentable version, but I still think the last version in this pull request achieves a good balance between extensibility and performance.

It's interesting to see that commit 2a8c0d5 does not seem to have an effect in your branch, as it had a large effect in mine.

**Comment by valerioformato** [comment]
I think I missed commit 2a8c0d5 entirely, my bad. I'll try when I can

However one of the first tests I did was removing all variants altogether and just manually call `Sphere::Hit` inside the hot path, at least on my setup this didn't yield any particular performance gain (maybe the compiler can see that the variant contains only one state and can optimize this away).
When there is more than one shape, however, the control flow doesn't change at all and prototyping becomes very easy, that's way I'd like to keep it this way.
On a related note, once you determine which is the closest sphere, cube, etc, don't you have also to check which shape is the first one to be hit? This becomes a 2-step process, I wonder if this can have any kind of impact as well.

**Pull request closed without merging**
